name: 'Build Apple App'
inputs:
 ProjectPath:
  required: false
  type: string
  description: "Path to .xcodeproj, or it's directory, if not in the current working directory. xcodebuild -project XYZ"
 Scheme:
  required: true
  type: string
  description: "Scheme of project to build. xcodebuild -scheme XYZ"
 Configuration:
  required: true
  type: string
  description: "Configuration of scheme (eg. Debug or Release). xcodebuild -configuration XYZ"
 Destination:
  required: true
  type: string
  description: "Scheme Destination, eg. platform=macOS. See output on failing runs for options. xcodebuild -destination XYZ"
 Sdk:
  required: false
  type: string
  description: "macos, ios, appletvos, visionos. xcodebuild -sdk XYZ"
 AdditionalParams:
  required: false
  type: string
  description: "Additional arguments to pass to xcodebuild"
 RewritePackageUrls:
  required: false
  type: string
  description: "Rewrite package urls before build. eg. to insert PAT to access private repositories. Usage; https://github.com/yourpackage=https://YOUR_SECRET_PAT@github.com/yourpackage;"


secrets:


runs:
  using: 'node20'
  # gr: hack to fail if not running on a mac
  pre: 'This action must run on macos runners'
  pre-if: runner.os != 'macos'
  main: 'Action.js'
